[package]
name = "zero_to_prod"
version = "0.1.0"
authors = ["Mihai Neagu"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[lib]
path = "src/lib.rs"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
reqwest = { version = "0.11", features = ["json"] }