version: '4.1'

services:
    app:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - ${SERVER_PORT-8080}:8080
        env_file:
            - .env
        volumes:
            - .:/app
            - /app/target
        command: tail -f /dev/null
        depends_on:
            - db
        networks:
            - internal
    db:
        image: postgres:13.1
        hostname: postgres
        ports:
            - ${DB_PORT-5432}:5432
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        env_file:
            - .env
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - internal
volumes:
    db_data:
networks:
    internal: